[package]
name = "mondradiko-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "mondradiko/core",
  "mondradiko/types",
  "mondradiko/wasmtime",
]

[dependencies]
mondradiko-core = { path = "./mondradiko/core/" }
mondradiko-types = { path = "./mondradiko/types/" }
