[package]
name = "mondradiko-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "mondradiko-core",
  "mondradiko-types",
]

[dependencies]
mondradiko-core = { path = "mondradiko-core" }
mondradiko-types = { path = "mondradiko-types" }
