[package]
name = "mondradiko-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.7", features = [ "derive" ] }
serde = { version = "^1.0", features = [ "derive" ] }
